### ISSUE TITLE
composer.borreli.com is OffLine

### ISSUE THREAD

**Issue by IGitSylvia** [pborreli/composer-service#129]
Hi, I am not sure if you guys have noticed but composer.borreli.com is currently is offline

Is there a new site?

**Comment by cordoval** [comment]
indeed it is down

bump @pborreli knock knock :blush:

**Comment by pborreli** [comment]
thanks for the notice, I'm aware indeed, having an issue with my ssl cert, I will put it back online on http tomorrow.

**Comment by pborreli** [comment]
https://composer.borreli.com/ is back !

**Comment by josegonzalez** [comment]
It's down again :(

**Comment by pborreli** [comment]
yes i'm aware of the problem, it's just hard for me to fix it as i'm traveling right now, will work on it asap !

**Comment by pborreli** [comment]
fixed !

**Comment by josegonzalez** [comment]
:+1:

**Comment by ngangchill** [comment]
It's down again :(
